sudo: required
dist: xenial
os: linux

language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - check

before_install:
  - sudo '.travis/ubuntu/setup_zfs_requirements.sh'

script:
  - sudo modprobe zfs
  - mkdir -p cmake-build && cd cmake-build
  - cmake ..
  - make
#  - ./tests/zectl_tests